---
- name: Install build-essential
  apt:
    name: build-essential
- name: Install libssl-dev
  apt:
    name: libssl-dev
- name: Install pip
  apt:
    name: python-pip
  become: yes
- name: Install libfontconfig
  apt:
    name: libfontconfig
  become: yes
- name: Set timezone
  command: timedatectl set-timezone "Europe/Warsaw"
  become: yes
