# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "test" do |test|
    test.vm.provider "virtualbox" do |vb|
      vb.customize [ "setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1" ]
      vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "test"
    end

    test.vm.box = "ubuntu/bionic64"
    test.vm.box_check_update = false
    test.vm.network :private_network, ip: "192.168.3.10"
    test.vm.hostname = "test"
    test.ssh.username = "vagrant"
    test.ssh.private_key_path = File.expand_path("~/.vagrant.d/insecure_private_key")
    test.ssh.insert_key = false
    test.hostsupdater.aliases = ['api.test.com']
    test.vm.network :forwarded_port, host: 19229 , guest: 19229
    test.vm.network :forwarded_port, host: 8080, guest: 5000
    test.vm.network :forwarded_port, host: 27017, guest: 27017
    test.vm.synced_folder "../", "/var/www/api", id: "vagrant-root",
      mount_options: ["dmode=777,fmode=777"]

    test.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "develop.yml"
    ansible.limit = "all"
  end
  end
end
