---
- name: Add node to repository
  shell: >
   curl -sL https://deb.nodesource.com/setup_10.x | bash -
  become: yes
- name: Install node
  apt:
    name: nodejs
  become: yes
- name: Install yarn package manager
  command: npm install -g yarn
  become: yes
- name: Install global packages
  command: yarn global add nodemon
  become: yes
- name: Install api dependencies
  command: chdir=/var/www/api yarn --ignore-engines
  become: yes
